version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
  redis:
    image: "redis:6.2.11"
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./docker/data/redis:/data
