version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --reload
